"""GENERATED by generate_adapter.py v1 -- do not edit by hand.

Harness state digest (sha256 over canonical local+global store documents):
839ff99478d02a68b5eb19023858f110503ff3498a2b35c2739f824c7604f8a9

Local entries: 0; global entries: 0.
Mapping v1: empty state -> balanced default decision rule.
"""

from __future__ import annotations

from typing import Any

from metering.policies import BalancedSearchPolicy


class GeneratedPolicy(BalancedSearchPolicy):
    """Balanced-split decision rule with a descriptor that records provenance."""

    name = "self-evolve-generated"
    version = "1"

    def descriptor(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "version": self.version,
            "configuration": {
                "strategy": "balanced",
                "tie_break": "public_catalogue_order",
                "harness_provenance": {
                    "generator_version": 1,
                    "harness_state_digest": "839ff99478d02a68b5eb19023858f110503ff3498a2b35c2739f824c7604f8a9",
                    "entries_local": 0,
                    "entries_global": 0,
                },
            },
            "seed_policy": {"kind": "none"},
        }


if __name__ == "__main__":
    raise SystemExit("adapter module; import GeneratedPolicy")
