"""GENERATED by generate_adapter.py v2 -- do not edit by hand.

Harness state digest (sha256 over canonical local+global store documents):
9b99989deca6125daedbed62bb3df438da4bda9670caa577af249c92774fd6af

Local entries: 4; global entries: 0.
Memory ids (context-only, mapped in v2): ["ipython-nested-quote-workaround", "qwen-evolve-artifact-location", "qwen-evolve-failclosed-design", "qwen-evolve-self-refine-state"]
Mapping v2: memory entries are provenance-only; decision rule stays balanced.
"""

from __future__ import annotations

from typing import Any

from metering.policies import BalancedSearchPolicy


class GeneratedPolicy(BalancedSearchPolicy):
    """Balanced-split decision rule with a descriptor that records provenance."""

    name = "self-evolve-generated"
    version = "2"

    def descriptor(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "version": self.version,
            "configuration": {
                "strategy": "balanced",
                "tie_break": "public_catalogue_order",
                "harness_provenance": {
                    "generator_version": 2,
                    "harness_state_digest": "9b99989deca6125daedbed62bb3df438da4bda9670caa577af249c92774fd6af",
                    "entries_local": 4,
                    "entries_global": 0,
                    "memory_ids": ["ipython-nested-quote-workaround", "qwen-evolve-artifact-location", "qwen-evolve-failclosed-design", "qwen-evolve-self-refine-state"],
                },
            },
            "seed_policy": {"kind": "none"},
        }


if __name__ == "__main__":
    raise SystemExit("adapter module; import GeneratedPolicy")
