"""Mechanically generate a Metering HarnessPolicy from Prime Agent harness state.

Step (1) of the qwen-evolve self-refinement loop.  The same generator code
runs for every harness state; the state is the only input.  Output is a
deterministic policy module whose descriptor records the exact state digest
that produced it, so before/after suite readings stay comparable.

Mapping rules (v2):
  * store absent or empty -> default strategy: balanced split,
    public-catalogue-order tie break (the unrefined default decision rule)
  * schema-1 store ({"schema", "entries", "refinements"}) with entries only
    of kind "memory" -> memories are mapped as CONTEXT-ONLY provenance:
    they describe the task, not diagnostic strategy, so the decision rule
    stays balanced; the memory ids and state digest are recorded in the
    descriptor so the state change is visible in every run manifest.
  * non-empty skill/subagent/prompt entries, unknown kinds, unknown
    top-level keys, or unknown schema -> FAIL CLOSED: refuse to generate
    rather than silently measure a state the mapping does not cover.

History:
  v1: empty/absent state only; flat legacy layout; fail closed otherwise.
  v2: parse schema-1 store layout; map memory entries (context-only).

Usage:
  python generate_adapter.py --session <session-id> --tag <tag>
  -> writes adapters/<tag>_policy.py + evidence/<tag>_state.json
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

GENERATOR_VERSION = 2
KINDS = ("memory", "skill", "subagent", "prompt")
MAPPED_KINDS: frozenset[str] = frozenset({"memory"})  # v2: memory mapped (context-only)
SCHEMA1_TOP_KEYS = frozenset({"schema", "entries", "refinements"})


def local_state_path(session: str) -> Path:
    return (
        Path.home()
        / ".prime/agent/session-artifacts"
        / session
        / "harness"
        / "harness_state.json"
    )


GLOBAL_STATE = Path.home() / ".prime/agent/harness" / "harness_state.json"


def load_state(path: Path) -> dict:
    if not path.exists():
        return {"exists": False, "raw": {}}
    raw = json.loads(path.read_text())
    if not isinstance(raw, dict):
        raise SystemExit(f"refusing: {path} is not a JSON object")
    return {"exists": True, "raw": raw}


def entries_of(store: dict) -> list[dict]:
    """Normalize a store to a list of {"kind", "id", "entry"} records.

    Handles the schema-1 layout (top-level "entries" mapping kind -> id ->
    entry) and the legacy flat layout (kind -> list of entries).  Fails
    closed on anything else.
    """
    if not store.get("exists"):
        return []
    raw = store["raw"]
    if "entries" in raw:
        if raw.get("schema") != 1:
            raise SystemExit(
                f"refusing: store schema {raw.get('schema')!r} is not 1; "
                "review the layout (bump GENERATOR_VERSION) before measuring"
            )
        unknown = sorted(set(raw) - SCHEMA1_TOP_KEYS)
        if unknown:
            raise SystemExit(
                f"refusing: store has unrecognized top-level key(s) {unknown}; "
                "update SCHEMA1_TOP_KEYS (bump GENERATOR_VERSION) before measuring"
            )
        entries = raw.get("entries") or {}
        if not isinstance(entries, dict):
            raise SystemExit("refusing: store 'entries' is not an object")
        unknown_kinds = sorted(set(entries) - set(KINDS))
        if unknown_kinds:
            raise SystemExit(
                f"refusing: store has unrecognized kind(s) {unknown_kinds}; "
                "update KINDS (bump GENERATOR_VERSION) before measuring"
            )
        refinements = raw.get("refinements") or []
        if not isinstance(refinements, list):
            raise SystemExit("refusing: store 'refinements' is not a list")
        out = []
        for kind in KINDS:
            bucket = entries.get(kind) or {}
            if not isinstance(bucket, dict):
                raise SystemExit(f"refusing: entries[{kind!r}] is not an object")
            for entry_id in sorted(bucket):
                out.append({"kind": kind, "id": entry_id, "entry": bucket[entry_id]})
        return out
    # legacy flat layout (v1): kind -> list of entries
    unknown = sorted(set(raw) - set(KINDS))
    if unknown:
        raise SystemExit(
            f"refusing: store has unrecognized key(s) {unknown}; "
            "update KINDS (bump GENERATOR_VERSION) before measuring"
        )
    out = []
    for kind in KINDS:
        for entry in raw.get(kind, []) or []:
            out.append({"kind": kind, "id": None, "entry": entry})
    return out


def canonical(obj) -> str:
    return json.dumps(obj, sort_keys=True, separators=(",", ":"))


TEMPLATE = '''"""GENERATED by generate_adapter.py v{gv} -- do not edit by hand.

Harness state digest (sha256 over canonical local+global store documents):
{digest}

Local entries: {n_local}; global entries: {n_global}.
Memory ids (context-only, mapped in v{gv}): {memory_ids}
Mapping v{gv}: memory entries are provenance-only; decision rule stays balanced.
"""

from __future__ import annotations

from typing import Any

from metering.policies import BalancedSearchPolicy


class GeneratedPolicy(BalancedSearchPolicy):
    """Balanced-split decision rule with a descriptor that records provenance."""

    name = "self-evolve-generated"
    version = "{gv}"

    def descriptor(self) -> dict[str, Any]:
        return {{
            "name": self.name,
            "version": self.version,
            "configuration": {{
                "strategy": "balanced",
                "tie_break": "public_catalogue_order",
                "harness_provenance": {{
                    "generator_version": {gv},
                    "harness_state_digest": "{digest}",
                    "entries_local": {n_local},
                    "entries_global": {n_global},
                    "memory_ids": {memory_ids},
                }},
            }},
            "seed_policy": {{"kind": "none"}},
        }}


if __name__ == "__main__":
    raise SystemExit("adapter module; import GeneratedPolicy")
'''


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--session", required=True, help="Prime Agent session id")
    parser.add_argument("--tag", required=True, help="tag for output names")
    args = parser.parse_args()

    base = Path(__file__).resolve().parent
    local = load_state(local_state_path(args.session))
    gstore = load_state(GLOBAL_STATE)
    local_entries = entries_of(local)
    global_entries = entries_of(gstore)
    all_entries = local_entries + global_entries

    unmapped = [e for e in all_entries if e["kind"] not in MAPPED_KINDS]
    if unmapped:
        kinds = sorted({e["kind"] for e in unmapped})
        raise SystemExit(
            f"refusing to generate: {len(unmapped)} harness entr(y/ies) of "
            f"unmapped kind(s) {kinds}; extend MAPPED_KINDS (bump "
            "GENERATOR_VERSION) first"
        )

    memory_ids = sorted(e["id"] for e in all_entries if e["kind"] == "memory" and e["id"])

    state_document = {
        "generator_version": GENERATOR_VERSION,
        "local_store": {"path": str(local_state_path(args.session)), **local},
        "global_store": {"path": str(GLOBAL_STATE), **gstore},
    }
    digest = hashlib.sha256(canonical(state_document).encode("utf-8")).hexdigest()

    out_dir = base / "adapters"
    out = out_dir / f"{args.tag}_policy.py"
    out.write_text(
        TEMPLATE.format(
            gv=GENERATOR_VERSION,
            digest=digest,
            n_local=len(local_entries),
            n_global=len(global_entries),
            memory_ids=json.dumps(memory_ids),
        )
    )
    state_document["digest"] = digest
    state_document["memory_ids"] = memory_ids
    (base / "evidence" / f"{args.tag}_state.json").write_text(
        json.dumps(state_document, indent=2, sort_keys=True) + "\n"
    )
    print(f"wrote {out}")
    print(f"harness_state_digest={digest}")
    print(f"entries: local={len(local_entries)} global={len(global_entries)}")
    print(f"memory_ids={memory_ids}")


if __name__ == "__main__":
    main()
