"""Metering: replayable measurement for a controlled hidden-fault world."""

from .calibration import (
    CalibrationFailure,
    CalibrationResult,
    run_calibration,
)
from .events import (
    EVENT_SCHEMA_VERSION,
    Action,
    Diagnose,
    DiagnosticObservation,
    Event,
    EventError,
    Finish,
    FinishObservation,
    Observation,
    RawActionCost,
    Repair,
    RepairObservation,
    VerificationObservation,
    Verify,
    action_from_dict,
    action_to_dict,
    observation_from_dict,
    observation_to_dict,
)
from .hidden_fault import (
    ActionValidation,
    DiagnosticTest,
    HiddenFaultError,
    HiddenFaultSpec,
    HiddenFaultWorld,
    InvalidActionError,
    PublicInstance,
)
from .policies import (
    BalancedSearchPolicy,
    HarnessPolicy,
    PolicyError,
    SeededRandomSearchPolicy,
    SequentialSearchPolicy,
    remaining_candidates,
)
from .provenance import (
    CONTROLLER_VERSION,
    METER_VERSION,
    PACKAGE_VERSION,
    VERIFIER_VERSION,
)
from .report import (
    ReportError,
    ReplayState,
    aggregate_reports,
    build_report,
    regenerate_report,
    replay_trace,
)
from .runner import (
    DEFAULT_ACTION_BUDGET,
    Controller,
    ControllerOutcome,
    RunResult,
    RunnerError,
    run_experiment,
    run_hidden_fault,
)
from .trace import (
    RunPaths,
    TraceError,
    TraceReader,
    TraceWriter,
    canonical_json,
    read_events,
    read_json,
)

__version__ = PACKAGE_VERSION

__all__ = [
    "Action",
    "ActionValidation",
    "BalancedSearchPolicy",
    "CalibrationFailure",
    "CalibrationResult",
    "Controller",
    "ControllerOutcome",
    "CONTROLLER_VERSION",
    "DEFAULT_ACTION_BUDGET",
    "Diagnose",
    "DiagnosticObservation",
    "DiagnosticTest",
    "EVENT_SCHEMA_VERSION",
    "Event",
    "EventError",
    "Finish",
    "FinishObservation",
    "HarnessPolicy",
    "HiddenFaultError",
    "HiddenFaultSpec",
    "HiddenFaultWorld",
    "InvalidActionError",
    "METER_VERSION",
    "Observation",
    "PACKAGE_VERSION",
    "PolicyError",
    "PublicInstance",
    "RawActionCost",
    "Repair",
    "RepairObservation",
    "ReplayState",
    "ReportError",
    "RunPaths",
    "RunResult",
    "RunnerError",
    "SeededRandomSearchPolicy",
    "SequentialSearchPolicy",
    "TraceError",
    "TraceReader",
    "TraceWriter",
    "VERIFIER_VERSION",
    "VerificationObservation",
    "Verify",
    "action_from_dict",
    "action_to_dict",
    "aggregate_reports",
    "build_report",
    "canonical_json",
    "observation_from_dict",
    "observation_to_dict",
    "read_events",
    "read_json",
    "regenerate_report",
    "remaining_candidates",
    "replay_trace",
    "run_calibration",
    "run_experiment",
    "run_hidden_fault",
]
